baseURL = 'https://dudung.github.io/rusn'
languageCode = 'en-us'
title = 'rusn'
theme = 'default'

enableEmoji = true

[pagination]
pagerSize = 20

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 0
  identifier = 'home'
  url = '/'
