baseURL = 'https://dudung.github.io/notes'
languageCode = 'en-us'
title = 'notes'
theme = 'default'

ignoreLogs = ['warning-goldmark-raw-html']
enableEmoji = true

[pagination]
pagerSize = 30

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Talks'
  weight = 0
  identifier = 'talks'
  url = '/tags/talks'
