baseURL = 'https://dudung.github.io/notes'
languageCode = 'en-us'
title = 'notes'
theme = 'default'

ignoreLogs = ['warning-goldmark-raw-html']
enableEmoji = true

[pagination]
pagerSize = 30

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 0
  identifier = 'home'
  url = '/'

[[menu.main]]
  name = 'Talks'
  weight = 1
  identifier = 'talks'
  url = '/talks'

[[menu.main]]
  name = 'Decks'
  weight = 2
  identifier = 'decks'
  url = '/decks'

[[menu.main]]
  name = 'Slides'
  weight = 3
  identifier = 'Slides'
  url = '/slides'
