baseURL = 'https://dudung.github.io/rusn'
languageCode = 'en-us'
title = 'rusn'
theme = 'default'

enableEmoji = true

[pagination]
pagerSize = 20

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 3
  identifier = 'home'
  url = '/'

[[menu.main]]
  name = 'Tags'
  weight = 2
  identifier = 'tags'
  url = '/tags'

[[menu.main]]
  name = 'Cats'
  weight = 1
  identifier = 'cats'
  url = '/categories'
